name: Continuous Integration

on:
  schedule:
    - cron: "0 5 * * *" # This will run the action every hour
  pull_request:
  push:
    branches:
      - main

jobs:
  update_starred_repos_section:
    name: Update the starred section
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: Install jq
        run: sudo apt-get install jq
    
      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.GH_SSH_KEY }}"

      - name: Fetch Starred Repositories
        run: |
          curl -s "https://api.github.com/users/zacharyrgonzales-portfolio/starred?per_page=5" | jq -r '.[] | "- [" + .name + "](" + .html_url + ")"' > starred_repos.md
      - name: Update README.md
        run: |
          sed -i '/<!--START:starred_repos-->/,/<!--END:starred_repos-->/d' README.md
          echo "<!--START:starred_repos-->" >> README.md
          cat starred_repos.md >> README.md
          echo "<!--END:starred_repos-->" >> README.md
      - name: Commit and Push
        run: |
          git config user.name "zacharyrgonzales-portfolio"
          git config user.email "${{ secrets.GH_EMAIL }}"
          git add README.md
          git commit -m "Updated Starred Repositories" || echo "No changes to commit"
          git push git@github.com:zacharyrgonzales-portfolio/zacharyrgonzales-portfolio.git
