name: Update Starred Repos

on:
  workflow_run:
    workflows: ["Prettier"]
    types:
      - completed
  schedule:
    - cron: "0 * * * *" # This will run the action every hour
  pull_request:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: Install jq
        run: sudo apt-get install jq
    
      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.GH_SSH_KEY }}"

      - name: Fetch Starred Repositories
        run: |
          curl -s "https://api.github.com/users/zacharyrgonzales-portfolio/starred?per_page=5" | jq -r '.[] | "- [" + .name + "](" + .html_url + ")"' > starred_repos.md
      - name: Update README.md
        run: |
          sed -i '/<!--START:starred_repos-->/,/<!--END:starred_repos-->/d' README.md
          echo "<!--START:starred_repos-->" >> README.md
          cat starred_repos.md >> README.md
          echo "<!--END:starred_repos-->" >> README.md
      - name: Commit and Push
        run: |
          git diff --exit-code || git commit -m "Updated Starred Repositories"
          git push git@github.com:zacharyrgonzales-portfolio/zacharyrgonzales-portfolio.git
